#include <stddef.h>

/*
 * Auto-generated by @ccss/compiler
 * Component: AppShell
 * GeneratedAt: 2026-03-20T04:48:57.769Z
 * State IDs:
 * - ccss:app-shell:app-shell:auth-modal-open
 * - ccss:app-shell:app-shell:new-post-modal-open
 */
const char* ccss_render_app_shell(void) {
  return "<div class=\"relative z-0 flex justify-center font-sans\"><input id=\"ccss:app-shell:app-shell:auth-modal-open\" class=\"ccss-state-input\" type=\"checkbox\"></input><input id=\"ccss:app-shell:app-shell:new-post-modal-open\" class=\"ccss-state-input\" type=\"checkbox\"></input><div class=\"bg-cax-surface text-cax-text flex min-h-screen max-w-full\"><div class=\"relative z-10\"><nav class=\"border-cax-border bg-cax-surface fixed right-0 bottom-0 left-0 z-10 h-12 border-t lg:relative lg:h-full lg:w-48 lg:border-t-0 lg:border-r\"></nav></div><main class=\"relative z-0 w-screen max-w-screen-sm min-w-0 shrink pb-12 lg:pb-0\"></main></div></div>";
}
